# -*- coding: utf-8 -*-
"""Ineuron_Assignment_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AH_ab62jPqXxb3Qu1TaR4i5GpaXmBn1f

#Q.1. What are keywords in python? Using the keyword library, print all the python keywords.
 Answer: Keywords in Python are reserved words that cannot be used as ordinary identifiers. They are used to define the syntax and structure of the Python language.
"""

#Program:
import keyword
print(keyword.kwlist)

"""# Q.2. What are the rules to create variables in python?
Answer:
1.	A variable name must start with a letter or the underscore character.
2.	A variable name cannot start with a number.
3.	A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ )
4.	Variable names are case-sensitive (age, Age and AGE are three different variables)

#Q.3. What are the standards and conventions followed for the nomenclature of variables in python to improve code readability and maintainability?
Answer: It would be good practice during the naming of  variables is to prioritize clarity and readability. Choose names that make your code self-explanatory and help others (including your future self) understand the purpose and functionality of the variables without needing to refer to additional documentation.

#Q.4. What will happen if a keyword is used as a variable name?
"""

#Answer:
False =20
Print(False)
#Output: SyntaxError: cannot assign to False. it will throw the error

"""#Q.5. For what purpose def keyword is used?
Answer: The def is used for creating the user defined function in python



"""

def greet():
    print("Hello World!")

greet()
#Output: Hello World!

"""#Q.6. What is the operation of this special character ‘\’?
 Answer:
     The special character \ in Python is known as the backslash. The backslash is used to escape certain special characters so that they can be included in a string as regular characters. For example, if you want to include a single quote or double quote within a string enclosed by the same type of quote, you can escape the quote using a backslash.

#Q.7. Give an example of the following conditions:
Answer:

(i) Homogeneous list : [1,2,3,4,5]

(ii) Heterogeneous set : {1,2,”Vikas”,True}

(iii) Homogeneous tuple : (1,2,4)

#Q.8. Explain the mutable and immutable data types with proper explanation & examples.
Answer:

Immutable Data Types:

Immutable data types are those whose values cannot be modified once they are created. Any operation that appears to modify an immutable object actually creates a new object with the modified value.
"""

#Examples

t = (1, 2, 3)
t.append(5)
print(t)  #AttributeError: 'tuple' object has no attribute 'append'. it will throw the error

"""Mutable Data Types:

Mutable data types are those whose values can be modified after they are created. Operations can directly modify the existing object without creating a new one. Examples of mutable data types in Python include:

"""

#Examples

lst = [1, 2, 3]
lst[1] = 5  # Modifying an element in the list
lst.append(4)  # Adding a new element
print(lst)  # Output: [1, 5, 3, 4]

"""#Q.9. Write a code to create the given structure using only for loop.

                 *
                ***
               *****
              *******
             *********




"""

#Program:

row = 10
k= row-1
for i in range(1,row,2):
    for j in range(k):
        print(end=" ")
    k -=1
    for j in range(1,i+1):
        print("*", end="")
    print("\r")

"""#Q.10. Write a code to create the given structure using while loop.
              |||||||||  
               |||||||
                |||||
                 |||
                  |


"""

#Program:

# python3 code to print pyramid pattern using while loop
n=0
i=9
k=0
while(i>=n):
  print(" " * (k) +"|" * i)
  i-=2
  k+=1